[8.0.1.0.0][partner_workflow_policy]
open-synergy/opnsynid-partner-contact pull request #102
Opened 2020-05-26 12:39 UTC by azmimr67

Partner workflow policy
Policy untuk mark as customer dan supplier
Untuk field yang di read only masih di mark di res_partner.py baris 46 sd 87

2020-05-26 13:32 UTC, mikevhe18 requested changes

2020-05-26 13:32 UTC, mikevhe18 commented on partner_workflow_policy/models/res_partner.py
> +from openerp import models, fields, api, _
Import "_(_Undescore_)" dihapus om karena tidak terpakai

2020-05-26 13:32 UTC, mikevhe18 commented on partner_workflow_policy/__openerp__.py
> +# Copyright 2020 OpenSynergy Indonesia
Tambahkan # Copyright 2020 PT Simetri Sinergi Indonesia

2020-05-26 13:32 UTC, mikevhe18 commented on partner_workflow_policy/models/res_partner.py
> +from openerp.exceptions import Warning as UserError
Dihapus Om karena tidak terpakai

2020-05-26 13:32 UTC, mikevhe18 commented on partner_workflow_policy/models/res_partner.py
> +    # )
Untuk field-field yang butuh di-readonly, dilakuinnya di view aja om pake attributes "attrs". Soalnya nanti di res.users akan jadi readonly juga dan membuat error

2020-05-26 13:32 UTC, mikevhe18 commented on partner_workflow_policy/models/res_partner.py
> +        compute="_compute_policy"
Tambahkan ",(koma)" diakhir

2020-05-26 13:32 UTC, mikevhe18 commented on partner_workflow_policy/models/res_partner.py
> +        compute="_compute_policy"
Tambahkan ",(koma)" diakhir

2020-05-26 13:32 UTC, mikevhe18 commented on partner_workflow_policy/models/res_partner.py
> +        compute="_compute_policy"
Tambahkan ",(koma)" diakhir

2020-05-26 13:32 UTC, mikevhe18 commented on partner_workflow_policy/models/res_partner.py
> +        compute="_compute_policy"
Tambahkan ",(koma)" diakhir

2020-05-26 13:32 UTC, mikevhe18 commented on partner_workflow_policy/models/res_partner.py
> +        compute="_compute_policy"
Tambahkan ",(koma)" diakhir

2020-05-26 13:32 UTC, mikevhe18 commented on partner_workflow_policy/models/res_partner.py
> +        compute="_compute_policy"
Tambahkan ",(koma)" diakhir

2020-05-26 13:32 UTC, mikevhe18 commented on partner_workflow_policy/models/res_partner.py
> +        compute="_compute_policy"
Tambahkan ",(koma)" diakhir

2020-05-26 13:32 UTC, mikevhe18 commented on partner_workflow_policy/views/res_partner_views.xml
> +                </xpath>
ditaro diatas aja om disatukan sama penambahan button

2020-05-26 13:32 UTC, mikevhe18 commented on partner_workflow_policy/views/res_partner_views.xml
> +                </xpath>
Tambahkan field-field yang mau di-readonly menggunakan attributes.
Cth:
```
<xpath expr="//field[@name='child_ids']" position="attributes">
    <attribute name="attrs">
        {'readonly':[('state','!=', 'draft')]}
    </attribute>
</xpath>
```

2020-05-27 03:50 UTC, azmimr67 commented on partner_workflow_policy/models/res_partner.py
> +from openerp import models, fields, api, _
done

2020-05-27 03:51 UTC, azmimr67 commented on partner_workflow_policy/__openerp__.py
> +# Copyright 2020 OpenSynergy Indonesia
done

2020-05-27 03:51 UTC, azmimr67 commented on partner_workflow_policy/models/res_partner.py
> +from openerp.exceptions import Warning as UserError
done

2020-05-27 03:52 UTC, azmimr67 commented on partner_workflow_policy/models/res_partner.py
> +        compute="_compute_policy"
done

2020-05-27 03:53 UTC, azmimr67 commented on partner_workflow_policy/models/res_partner.py
> +        compute="_compute_policy"
done

2020-05-27 03:53 UTC, azmimr67 commented on partner_workflow_policy/models/res_partner.py
> +        compute="_compute_policy"
done

2020-05-27 03:53 UTC, azmimr67 commented on partner_workflow_policy/models/res_partner.py
> +        compute="_compute_policy"
done

2020-05-27 03:53 UTC, azmimr67 commented on partner_workflow_policy/models/res_partner.py
> +        compute="_compute_policy"
done

2020-05-27 03:53 UTC, azmimr67 commented on partner_workflow_policy/models/res_partner.py
> +        compute="_compute_policy"
done

2020-05-27 03:54 UTC, azmimr67 commented on partner_workflow_policy/models/res_partner.py
> +        compute="_compute_policy"
done

2020-05-27 03:56 UTC, azmimr67 commented on partner_workflow_policy/views/res_partner_views.xml
> +                </xpath>
Jika dipindahkan ke atas posisinya tidak bisa di sebelah sales_purchase.
Jadi saya biarkan tetap disini saja

2020-05-27 04:01 UTC, azmimr67 commented on partner_workflow_policy/views/res_partner_views.xml
> +                </xpath>
done

2021-12-27 01:40 UTC, closed without merging